# Generated by Django 4.1.3 on 2023-01-18 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_department_remove_employee_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('licence_plate', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
                ('details', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.person')),
            ],
        ),
    ]
