# Generated by Django 4.1.3 on 2023-01-19 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_person_nip_alter_person_pesel'),
        ('cars', '0003_remove_car_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='person',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='users.person'),
        ),
    ]
