# Generated by Django 4.1.3 on 2023-01-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='person',
        ),
        migrations.AlterField(
            model_name='car',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
