# Generated by Django 4.1.3 on 2023-01-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_car_person_alter_car_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Diesel', 'Dielsel'), ('Petrol', 'Petrol')], max_length=10, null=True),
        ),
    ]
