# Generated by Django 4.1.3 on 2023-01-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='licence_plate',
            field=models.CharField(max_length=7),
        ),
    ]
