# Generated by Django 4.1.3 on 2023-01-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_fuel_alter_car_licence_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Gasoline', 'Gasoline')], max_length=10, null=True),
        ),
    ]
