# Generated by Django 4.1.3 on 2023-01-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_car_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
