# Generated by Django 4.1.3 on 2023-01-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department_remove_employee_person_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'persons'},
        ),
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='nip',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
