# Generated by Django 4.1.3 on 2023-01-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_person_nip_alter_person_pesel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='nip',
        ),
        migrations.RemoveField(
            model_name='person',
            name='pesel',
        ),
        migrations.AddField(
            model_name='person',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='company',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
