# Generated by Django 4.1.3 on 2023-01-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('client', models.CharField(help_text='Imię i Nazwisko', max_length=150)),
                ('price', models.IntegerField()),
                ('release_date', models.DateField(help_text='Format YYYY-MM-DD', null=True)),
            ],
            options={
                'verbose_name_plural': 'contracts',
            },
        ),
    ]
