# Generated by Django 4.1.3 on 2023-01-22 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_car_person_alter_car_details'),
        ('contracts', '0002_contract_department_contract_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='vin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
    ]
